zep_add_test(zep_codegen_llvm_tests
    DEPENDS zep_codegen_llvm zep_codegen_api zep_compiler zep_hir zep_frontend zep_common zep_test_support zep_codegen_test_support zep_frontend_test_support
)

zep_add_benchmark(zep_codegen_llvm_benchmarks
    DEPENDS zep_codegen_llvm zep_codegen_api zep_compiler zep_hir zep_frontend zep_common zep_test_support zep_codegen_test_support
)
add_subdirectory(support)
