import std.core.type.i8
import std.core.type.i16
import std.core.type.i32
import std.core.type.i64
import std.core.type.u8
import std.core.type.u16
import std.core.type.u32
import std.core.type.u64
import std.core.type.f32
import std.core.type.f64
import std.core.type.boolean
import std.core.type.char
import std.core.type.cstr
import std.core.type.void
import std.core.type.never
import std.core.type.any
import std.core.type.Integer
import std.core.type.Float
import std.core.type.Boolean
import std.core.type.Char
import std.core.type.CStr
import std.core.type.Array
