option(ZEP_ENABLE_ASAN "Enable Address Sanitizer" OFF)
option(ZEP_ENABLE_UBSAN "Enable Undefined Behavior Sanitizer" OFF)
option(ZEP_ENABLE_TSAN "Enable Thread Sanitizer (incompatible with ASan)" OFF)
option(ZEP_ENABLE_MSAN "Enable Memory Sanitizer (incompatible with ASan/TSan)" OFF)

function(zep_set_sanitizers target)
    if(ZEP_ENABLE_ASAN)
        message(STATUS "Address Sanitizer enabled for ${target}")
        target_compile_options(${target} PRIVATE -fsanitize=address -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE -fsanitize=address)
    endif()

    if(ZEP_ENABLE_UBSAN)
        message(STATUS "Undefined Behavior Sanitizer enabled for ${target}")
        target_compile_options(${target} PRIVATE -fsanitize=undefined)
        target_link_options(${target} PRIVATE -fsanitize=undefined)
    endif()

    if(ZEP_ENABLE_TSAN)
        if(ZEP_ENABLE_ASAN)
            message(FATAL_ERROR "TSan and ASan cannot be used together")
        endif()
        message(STATUS "Thread Sanitizer enabled for ${target}")
        target_compile_options(${target} PRIVATE -fsanitize=thread)
        target_link_options(${target} PRIVATE -fsanitize=thread)
    endif()

    if(ZEP_ENABLE_MSAN)
        if(ZEP_ENABLE_ASAN OR ZEP_ENABLE_TSAN)
            message(FATAL_ERROR "MSan cannot be used together with ASan or TSan")
        endif()
        message(STATUS "Memory Sanitizer enabled for ${target}")
        target_compile_options(${target} PRIVATE -fsanitize=memory -fno-omit-frame-pointer)
        target_link_options(${target} PRIVATE -fsanitize=memory)
    endif()
endfunction()
